# Site settings
title: Blackstone Engineering
email: austin@blackstoneengineering.com
url: https://blackstoneengineering.github.io/blackstoneengineering.com
description: "Blackstone Engineering is a IoT consulting firm that specializes in bringing awesome ideas to life."
keywords: "Blackstone Engineering, IoT, Internet Of Things, consultant"
skills: "IoT Development - Embedded Engineering - World Domination"
meta_author: Blackstone Austin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 141414 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Blackstone Engineering LLC
  location: IRL
  social:  Digital
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/engineer_austin
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/blackstoneengineering
  - title: linkedin
    url: http://www.linkedin.com/in/austinblackstone

# Postal address (add as many lines as necessary)
address:
  - line: Austin TX
  - line: Tokyo Japan

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
